name: docs

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache conda
      id: cache-conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}

    - name: Setup conda, install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        channel-priority: strict
        environment-file: environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Build docs
      run: |
         # Remove old _sources and _static directory
         rm -rf ./docs/_sources;
         rm -rf ./docs/_static;
         # Execute the document build with conda
         $CONDA/envs/anaconda-client-env/bin/sphinx-build -M html ./docs/source ./docs;
         # Move docs into root directory
         mv ./docs/html/* ./docs; 
         # Move buildinfo 
         mv ./docs/html/.buildinfo ./docs;
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Auto-build documentation

        # Optional branch name where commit should be pushed to
        # Defaults to the current branch
        branch: main

        # Optional options appended to `git-commit`
        # See https://git-scm.com/docs/git-commit for a list of available options
        #commit_options: 'BLAHBLAH'

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: docs/*

        # Optional local file path to the repository
        # Defaults to the root of the repository
        repository: .

        # Optional commit user and author settings
        #commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
        #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

        # Optional tag message
        # Action will create and push a new tag to the remote repository and the defined branch
        #tagging_message: 'v1.0.0'

        # Optional options appended to `git-push`
        # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
        push_options: '--force'

        # Optional: Disable dirty check and always try to create a commit and push
        #skip_dirty_check: true

        # Optional: Skip internal call to `git fetch`
        #skip_fetch: true
